plugins:
  - jekyll-archives
  - liquid_pluralize
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "azure-pipelines.yml"
permalink: /:categories/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layouts:
    year: archiveYear
    month: archiveMonth
    day: archiveDay
  permalinks:
    year: '/news/during/:year/'
    month: '/news/during/:year/:month/'
    day: '/news/during/:year/:month/:day/'
collections:
  posts:
    permalink: '/news/during/:year/:month/:day/:title'