Parameters:
  BucketName:
    Description: The name of the bucket where the site will be stored.
    Type: String
    MinLength: 3
    MaxLength: 63

  ErrorDocument:
    Description: The path to the error document within the bucket.
    Type: String

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: !Ref ErrorDocument
      Tags:
        - Key: staticSite
          Value: !Ref BucketName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Sid: PublicReadForGetBucketObjects
            Principal:
              AWS: '*'
            Resource: !Sub "${WebBucket.Arn}/*"

  BucketUploader:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${BucketName}-Uploader"
      Policies:
        - PolicyName: BucketUpdatePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt WebBucket.Arn
                  - !Sub "${WebBucket.Arn}/*"
      Tags:
        - Key: staticSite
          Value: !Ref BucketName

  UploaderAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 1
      Status: Active
      UserName: !Ref BucketUploader

  UploaderAccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/site/${BucketName}/uploader"
      Description: Credentials used to upload new versions of the site.
      SecretString: !Sub '{"accessKey":"${UploaderAccessKey}","secretKey":"${UploaderAccessKey.SecretAccessKey}"}'
      Tags:
        - Key: staticSite
          Value: !Ref BucketName

Outputs:
  WebsiteURL:
    Value: !GetAtt WebBucket.WebsiteURL
    Description: S3 URL for the website
