plugins:
  - jekyll-archives
  - jekyll-feed
  - liquid_pluralize
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
title: wadny.com
description: "it looks good in yellow-that-Kottke-used-to-use-but-it’s-mine-now"
author:
  name: David
timezone: "America/New_York"
url: "https://wadny.com"
feed:
  path: "/news/everything.atom"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "humor_articles"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "humor_logs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layouts:
    year: archiveYear
    month: archiveMonth
    day: archiveDay
  permalinks:
    year: '/news/during/:year/'
    month: '/news/during/:year/:month/'
    day: '/news/during/:year/:month/:day/'
collections:
  humor_articles:
    permalink: '/humor/article/:title/'
    output: true
  humor_logs:
    permalink: '/humor/log/:title/'
    output: true
  posts:
    permalink: '/news/during/:year/:month/:day/:title/'