# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "jekyll", "~> 4.0"

group :jekyll_plugins do
    gem "jekyll-archives"
    gem "jekyll-feed"
    gem "liquid_pluralize"
end

gem "wdm", "~> 0.1.1", platforms: :windows
gem "tzinfo-data", "~> 1.2", platforms: :windows