name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: src
        bundler-cache: true
    - run: bundle install
      working-directory: src
    - run: bundle exec jekyll build
      working-directory: src
    - run: >-
        bundle exec htmlproofer
          --assume-extension
          --check-html
          --disable-external
          --alt-ignore "/graphics/logo.gif"
          --file-ignore "/\/design\/summary\/.+\/.+/","/\/design\/.+\/demo\/.+/"
          ./_site
      working-directory: src