name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: src
        bundler-cache: true
    - run: bundle install
      working-directory: src
    - run: bundle exec jekyll build
      working-directory: src
    - uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.WADNY_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.WADNY_UPLOADER_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.WADNY_UPLOADER_SECRET }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'src/_site'