name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        working-directory: src
        bundler-cache: true
    - run: bundle install
    - run: bundle exec jekyll build